- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: true
  tags:
    - deploy
- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
  become: true
  tags:
    - deploy
